### ISSUE TITLE
Variable.less bad variable  updated

### ISSUE THREAD

**Issue by bloublou** [lukemadera/grunt-font-awesome-vars#1]
Variables.less of font-awesome v4.0.3 contains two lines

@fa-font-path:        "../fonts";
//@fa-font-path:        "//netdna.bootstrapcdn.com/font-awesome/4.0.3/fonts"; // for referencing Bootstrap CDN font files directly

when replacing on variable.less file it update second line in comment by a @fa-font-path base on grunt config, example : 

@fa-font-path:        "../fonts";
@fa-font-path: "./vendor/font-awesome/fonts";

It should be replace the first @fa-font-path and let the second one intact.

**Comment by lukemadera** [comment]
Good catch @bloublou - there's a few ways to deal with this:
1. remove ALL @fa-font-path references (commented or otherwise) then add in the correct one - this will be foolproof but will wipe any comments (though that shouldn't be a big deal right?)
2. search from the bottom to find the first instance of @fa-font-path that is NOT within a comment (would have to handle both line comments and block comments) and replace that last non-commented one. These would leave comments intact but is a bit more complicated / error prone.

I'll likely go with option 1 but if you have a strong preference otherwise let me know.

**Comment by lukemadera** [comment]
So actually this shouldn't have given an error in the first place but it's updated https://github.com/lukemadera/grunt-font-awesome-vars/commit/367ffc4f1cfa8eea1bf71bd211dfac70ba48b97f
